# name: FaceGate Backend CI

# on:
#   push:
#     branches:
#       - main
#       - master
#       - development

#   pull_request:
#     branches:
#       - main
#       - master
#       - development

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: api

#     steps:

#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install Dependencies
#         run: npm install

#       - name: Build Project
#         run: npm run build

#       - name: Run Tests
#         run: npm test
#         continue-on-error: true
